### ISSUE TITLE
Uncaught Error: (regl) context lost

### ISSUE THREAD

**Issue by mooter** [ojack/atom-hydra#6] opened 2018-10-07 06:45 UTC
[Enter steps to reproduce:]
/* (I got this error in Chrome as well.  Firefox just crashes the browser.  It happens like 5 minutes after I load hydra and then I have to refresh the browser or restart Atom.  Graphic Drivers up to date */
1. ...
2. ...

**Atom**: 1.31.2 x64
**Electron**: 2.0.7
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [atom-hydra](https://github.com/ojack/atom-hydra) package 0.2.8

### Stack Trace

Uncaught Error: (regl) context lost

```
At C:\Users\Jasn\.atom\packages\atom-hydra\node_modules\regl\dist\regl.js:49

Error: (regl) context lost
    at Function.raise (/packages/atom-hydra/node_modules/regl/dist/regl.js:47:15)
    at /packages/atom-hydra/node_modules/regl/dist/regl.js:9396:17)
    at passes.forEach (/packages/atom-hydra/node_modules/hydra-synth/src/output.js:196:38)
    at Array.forEach (<anonymous>)
    at Output.tick (/packages/atom-hydra/node_modules/hydra-synth/src/output.js:196:15)
    at HydraSynth.tick (/packages/atom-hydra/node_modules/hydra-synth/index.js:300:17)
    at /packages/atom-hydra-master/lib/main.js:216:20)
    at emitOne (events.js:116:13)
    at Engine.emit (events.js:211:7)
    at Engine.tick (/packages/atom-hydra/node_modules/raf-loop/index.js:42:10)
```

### Commands

```
     -0:55.6.0 atom-hydra:evalLine (input.hidden-input)
     -0:53.3.0 core:backspace (input.hidden-input)
     -0:52.5.0 atom-hydra:evalLine (input.hidden-input)
     -0:48.7.0 core:backspace (input.hidden-input)
     -0:48 atom-hydra:evalLine (input.hidden-input)
     -0:43.5.0 core:backspace (input.hidden-input)
     -0:39.9.0 atom-hydra:evalLine (input.hidden-input)
     -0:36.4.0 core:delete (input.hidden-input)
     -0:35.5.0 atom-hydra:evalLine (input.hidden-input)
  2x -0:32.7.0 core:backspace (input.hidden-input)
     -0:29.6.0 core:move-left (input.hidden-input)
     -0:28.5.0 atom-hydra:evalLine (input.hidden-input)
     -0:25 core:backspace (input.hidden-input)
     -0:24.2.0 atom-hydra:evalLine (input.hidden-input)
  2x -0:22.5.0 core:backspace (input.hidden-input)
     -0:21.8.0 atom-hydra:evalLine (input.hidden-input)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-hydra 0.2.8 
neon-cursor 1.6.0 
neon-selection 0.3.2 
atom-ternjs 0.18.3 
auto-detect-indentation 1.3.0 
autocomplete-modules 2.2.2 
busy-signal 1.4.3 
intentions 1.1.5 
linter 2.2.0 
linter-eslint 8.4.1 
linter-ui-default 1.7.1 
neon-syntax 0.3.7 
pigments 0.40.2 
script 3.18.1 
sync-settings 0.8.6 
tidal-autocode 0.6.4 
tidalcycles 0.12.1 
todo-show 2.3.2 
```

**Comment by ojack** [comment] 2019-04-22 23:46
@mooter any update on this / does it still happen?

**Comment by ojack** [comment] 2019-08-07 00:33
CLosing this for now because there is not enough information to reproduce!

**Closed by ojack** 2019-08-07 00:33 UTC

**Comment by carltesta** [comment] 2021-11-25 20:38
I'm getting this error running atom-hydra on Ubuntu Studio 21.04. It happens regularly after a few minutes. I'm running the following code when it happens:
`speed = 0.25;
shape([3,6,1,10])
	.scrollX(1, 0.5)
	.modulateScale(noise(1, 0.1, 1.5).color(1, 1, 0), 0.9)
	.modulate(o0, 0.9)
	.scale([1,2,0.2,3].smooth())
//.colorama([0.1,1.5].smooth())
	.out()`

**Comment by carltesta** [comment] 2021-11-25 20:45
Here's the error report:

1. ... run the following code for a few minutes to reproduce:
`speed = 0.25; shape([3,6,1,10]) .scrollX(1, 0.5) .modulateScale(noise(1, 0.1, 1.5).color(1, 1, 0), 0.9) .modulate(o0, 0.9) .scale([1,2,0.2,3].smooth()) //.colorama([0.1,1.5].smooth()) .out()`

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: Ubuntu 21.04
**Thrown From**: [atom-hydra](https://github.com/ojack/atom-hydra) package 0.3.6


### Stack Trace

Uncaught Error: (regl) context lost

```
At /home/carl/.atom/packages/atom-hydra/node_modules/regl/dist/regl.js:49

Error: (regl) context lost
    at Function.raise (/packages/atom-hydra/node_modules/regl/dist/regl.js:47:15)
    at /packages/atom-hydra/node_modules/regl/dist/regl.js:9966:17)
    at Output.tick (/packages/atom-hydra/node_modules/hydra-synth/src/output.js:121:8)
    at HydraRenderer.tick (/packages/atom-hydra/node_modules/hydra-synth/hydra-synth.js:427:19)
    at /packages/atom-hydra/lib/main.js:234:20)
    at Engine.emit (events.js:223:5)
    at Engine.tick (/packages/atom-hydra/node_modules/raf-loop/index.js:42:10)
```

### Commands

```
     -8:28.2.0 tidalcycles:eval (input.hidden-input)
  9x -8:21.5.0 core:backspace (input.hidden-input)
     -8:19.6.0 tidalcycles:eval (input.hidden-input)
  3x -8:17.8.0 core:move-left (input.hidden-input)
     -8:16.1.0 core:backspace (input.hidden-input)
  3x -8:14.2.0 core:move-right (input.hidden-input)
  2x -8:13.5.0 core:backspace (input.hidden-input)
  6x -8:12.9.0 core:move-left (input.hidden-input)
     -8:10.9.0 core:backspace (input.hidden-input)
  3x -8:10.5.0 core:move-left (input.hidden-input)
     -8:08.1.0 tidalcycles:eval (input.hidden-input)
     -8:03.0 tidalcycles:eval-multi-line (input.hidden-input)
     -7:20.4.0 tidalcycles:eval (input.hidden-input)
  2x -7:16.5.0 core:save (input.hidden-input)
     -7:10.3.0 window:toggle-full-screen (input.hidden-input)
     -6:13 core:copy (input.hidden-input)
```

### Non-Core Packages

```
atom-hydra 0.3.6 
ftp-remote-edit 0.18.2 
tidalcycles 3.16.17 
```
